debug: 
	gcc -ggdb -Wall -O3 spuriousC.c -o spuriousC -I../ViennaRNA-1.8.5/H -L../ViennaRNA-1.8.5/lib -lRNA -lm
all: 
	gcc -Wall -O3 spuriousC.c -o spuriousC -I../ViennaRNA-1.8.5/H -L../ViennaRNA-1.8.5/lib -lRNA -lm