#!/bin/sh
CODEPATH=$HOME/app  #$HOME/share/infomachine2  # use ~/app for forwards-compatibility
cd ${CODEPATH}
echo "-------------------------------------"
echo "| DyNAMiC Workbench                 |"
echo "-------------------------------------"
echo "`date` - Starting server..."
echo "`date` - Working directory: `pwd`"
echo "`date` - Environment ${NODE_ENV}"

MONGOPATH=/usr/bin/mongod
# export NODEPATH=$HOME/local/node/bin/node
# export NODEPATH=/usr/bin/node
NODEPATH="`which node`"

CONFIGFILE=~/workbench-config 
echo "`date` - Searching for config file in $CONFIGFILE"
if [ -f $CONFIGFILE ]
	then
			echo "`date` - Loading config from $CONFIGFILE."
		. $CONFIGFILE
fi

echo "`date` - Starting nodejs (${NODEPATH})"
${NODEPATH} --debug app.js

