# This Makefile is part of the NUPACK software suite
# Copyright (c) 2007 Caltech. All rights reserved.
#
# Makefile for making all of NUPACK
#
# The src/design, src/thermo and src/shared directories are made.


all: 	
	$(MAKE) -C src/

clean: 
	$(MAKE) -C lib/ clean
	$(MAKE) -C src/ clean
	

