#!/usr/bin/env node
var auth = require('../../server/auth.js'),
	User = auth.User,
	program = require('commander'),
	util = require('util');

program
	.option('-a, --active', 'Activate user')
	.option('-A, --admin', 'Make user an administrator')
	.option('-n, --full <name>', 'Change the user\'s name')
	.option('-e, --email <email>', 'Change the user\'s email; note that this won\'t move their home directory')
	.option('-p, --password <password>', 'Change the user\'s password; note that this will also change the user\'s salt')
	.option('-i, --institution [institution]', 'Change the user\'s institution');
	
program
	.command('show [email]')
	.description('Show a user\'s data, or show all users')
	.action(function(email) {		
		query = {}
		if (!!email) {
			query.email = email;
		}
		User.find(query,function(err, rows) {
			if (err) throw err;
			console.log(util.inspect(rows, false, 3, true));
			process.exit(0);
		});
	});

program
	.command('delete <email>')
	.description('Delete a user')
	.action(function(email) {
		User.remove({'email': email},function(err, numAffected) {
			if (err) throw err;
			console.log("Deleted %d user(s)", numAffected);
			process.exit(0);
		});
	});

program
	.command('edit <email>')
	.description('Edit a user\'s data')
	.action(function(email) {

		var data = {}
		if (!!program.full) data.name = program.full; 
		if (!!program.email) data.email = program.email; 
		if (!!program.institution) data.institution = program.institution; 
		if (program.active !== undefined) data.active = program.active; 
		if (program.admin !== undefined) data.admin = program.admin; 
		if (program.password !== undefined) {
			var p = auth.changePassword(program.password);
			data.salt = p.salt;
			data.password = p.password;
		}
		if (!email) {
			console.error("Must provide an email address!");
		}

		User.update({'email': email},data,function(err, numAffected) {
			if (err) throw err;
			console.log(util.inspect(data, false, 1, true));
			console.log("Updated %d user(s)", numAffected);
			process.exit(0);
		});
	});


program.parse(process.argv);
