#!/usr/bin/env node
var auth = require('../../server/auth.js'),
	User = auth.User,
	program = require('commander'),
	util = require('util'),
	fs = require('fs');

program
	.option('-a, --active', 'Activate user')
	.option('-A, --admin', 'Make user an administrator')
	.option('-n, --full <name>', 'Change the user\'s name')
	.option('-e, --email <email>', 'Change the user\'s email; note that this won\'t move their home directory')
	.option('-p, --pass <password>', 'Change the user\'s password; note that this will also change the user\'s salt')
	.option('-i, --institution [institution]', 'Change the user\'s institution');
	
program
	.command('show [email]')
	.description('Show a user\'s data, or show all users')
	.action(function(email) {		
		query = {}
		if (!!email) {
			query.email = email;
		}
		User.find(query,function(err, rows) {
			if (err) throw err;
			console.log(util.inspect(rows, false, 5, true));
			process.exit(0);
		});
	});

program
	.command('delete <email>')
	.description('Delete a user')
	.action(function(email) {
		User.remove({'email': email},function(err, numAffected) {
			if (err) throw err;
			console.log("Deleted %d user(s)", numAffected);
			process.exit(0);
		});
	});

program
	.command('edit <email>')
	.description('Edit a user\'s data')
	.action(function(email) {
		var data = {}
		if (!!program.full) data.name = program.full; 
		if (!!program.email) data.email = program.email; 
		if (!!program.institution) data.institution = program.institution; 
		if (program.active !== undefined) data.active = program.active; 
		if (program.admin !== undefined) data.admin = program.admin; 
		if (program.pass !== undefined) {
			var p = auth.changePassword(program.pass);
			data.salt = p.salt;
			data.password = p.password;
		}
		if (!email) {
			console.error("Must provide an email address!");
		}

		User.update({'email': email},data,function(err, numAffected) {
			if (err) throw err;
			console.log(util.inspect(data, false, 1, true));
			console.log("Updated %d user(s)", numAffected);
			process.exit(0);
		});
	});

program
	.command('export')
	.description('Exports all users to a JSON file')
	.action(function() {		
		User.find({},function(err, rows) {
			if (err) throw err;
			rows = rows.map(function(row) {
				var r = row;
				r["_id"] = undefined;
				return r;
			})
			console.log(JSON.stringify(rows, null, '\t'));
			process.exit(0);
		});
	});

program
	.command('import')
	.description('Import a set of users from a JSON file on stdin')
	.action(function () {
		var json = fs.readFileSync('/dev/stdin').toString(),
			data = JSON.parse(json), 
			args;

		console.log(util.inspect(data, false, 5, true));
		// console.log(JSON.stringify(data));

		if (! (data instanceof Array)) {
			throw new Error("Unable to import data; must be an array of users. ")
		}

		args = data.concat([function (err) {
			if (err) throw err;
			console.log("Imported %d user(s)", arguments.length - 1)
			process.exit(0);
		}])

		User.create.apply(User, args );
	})

program.parse(process.argv);
